### ISSUE TITLE
camera 

### ISSUE THREAD

**Issue by Mahran55** [collinswakholi/SFM_3D_pipeline#1]
can you help me to know is the camera to use is specific or not? and if so what is its resolution and can I use any camera?

**Comment by collinswakholi** [comment]
The camera does not matter. For my use case I tested with images of resolution 2464x2048, and 1024x1024

**Comment by Mahran55** [comment]
> can you help me to know is the camera to use is specific or not? and if so what is its resolution and can I use any camera?

**Comment by Mahran55** [comment]
thanks but now i have a new problem
